// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwvgSR78TKMKq36MuJXzh2jEsJ-RGebw',
    appId: '1:136430869259:web:2cfcfd1edf653ee1a5a00e',
    messagingSenderId: '136430869259',
    projectId: 'applogist-chat',
    authDomain: 'applogist-chat.firebaseapp.com',
    storageBucket: 'applogist-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2OznhzNSLi3qHwKVCNa7DLQq_YiKedg',
    appId: '1:136430869259:android:269decf2f19f22c7a5a00e',
    messagingSenderId: '136430869259',
    projectId: 'applogist-chat',
    storageBucket: 'applogist-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS4NuveDOWG4I4L2CN8jkNvqjo6sc7geI',
    appId: '1:136430869259:ios:9963e4d6d969b835a5a00e',
    messagingSenderId: '136430869259',
    projectId: 'applogist-chat',
    storageBucket: 'applogist-chat.appspot.com',
    iosClientId: '136430869259-srjb17nc49esr097f0mnf0n5hnrnbpc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFirebase',
  );
}
